common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='common/login.html'), name='logout'),
    path('signup', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('common.urls')),
    path("encryption/", include('encryption.urls')),
    path("download/", include("download.urls")),
    path("py/", include("py.urls")),
]

encryption/urls.py
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'encryption'
urlpatterns = [
    path('', views.index, name='index'),
    #path('encryption', views.encryption, name='encryption'),
    path('mydrive', views.mydrive, name='mydrive'),
    path('download/<str:file_content>', views.download, name='download'),
    path('send/<str:file_content>', views.send, name='send'),
    path('delete/<str:file_content>', views.delete, name='delete'),
]

py/urls.py
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'py'
urlpatterns = [
    path('', views.index, name='index'),
    #path('encryption', views.encryption, name='encryption'),

]

encryption/models.py
from django.db import models
from django.contrib.auth.models import User

class enfile(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    send_user = models.CharField(null=True, max_length=20)
    file_date = models.DateTimeField(auto_now=True)
    file_text = models.TextField(null=True, max_length=100)
    file_content = models.FileField(null=True)

    def __str__(self):
        return self.file_content

encryption/forms.py
from django import forms

class UploadFileForm(forms.Form):
    id = forms.IntegerField()
    name = forms.CharField(max_length=50)
    fileinput = forms.FileField()
    key = forms.CharField(max_length=32)

encryption/views.py
import os
import sys
import hashlib
import io
import shutil
import urllib.parse
from .models import enfile
from datetime import datetime
from Crypto.Hash import SHA256 as SHA
from Crypto.Cipher import AES
from django.conf import settings
from django.http import FileResponse
from django.http import HttpResponse
from common.forms import UserForm
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.utils.datastructures import MultiValueDictKeyError

def index(request):
    return render(request, 'encryption/index.html')


#def encryption(request):
 #   return render(request, 'encryption/encryption.html')

def mydrive(request):
    result = ""
    if request.method == 'POST':
        f_text = request.POST['text']
        file = request.FILES.get('fileinput')

        if not file:
            return redirect('encryption:index')

        user_directory_path = os.path.join(settings.MEDIA_ROOT, str(request.user.username))
        if not os.path.exists(user_directory_path):
            os.makedirs(user_directory_path)
        file_path = os.path.join(user_directory_path, file.name)

        file_name_parts = os.path.splitext(file.name)
        file_names = os.listdir(user_directory_path) 

        if file_name_parts[1] != ".zip":
            result = 'not zip'
            content = {'result': result}
            return render(request, 'encryption/index.html', content)
        
        for i in range(len(file_names)):
            if file_names[i] == file.name:
                result = 'aleady file'
                content = {'result': result}
                return render(request, 'encryption/index.html', content)

        if not result:
            with open(file_path, "wb") as f:
                f.write(file.read())
            result = 'success upload'
                    
            e = enfile(user_id_id=request.user.id, file_text=f_text, file_content=file.name)
            e.save()

    enlist = enfile.objects.filter(user_id=request.user.id)
    content = {'result': result, 'enlist': enlist}
    return render(request, 'encryption/mydrive.html', content)

def download(request, file_content):
    user_directory_path = os.path.join(settings.MEDIA_ROOT, str(request.user.username))

    if file_content in os.listdir(user_directory_path):
        fs = FileSystemStorage(user_directory_path)
        response = FileResponse(fs.open(file_content, 'rb'))
        file_name = str(file_content)
        response['Content-Disposition'] =  'attachment; filename="{}"'.format(file_name)
        return response

    return redirect('encryption:mydrive')

def send(request, file_content):
    send_name = request.GET['sendid']
    send_id = None
    user_list = User.objects.all()
    for u in user_list:
        if u.username == send_name:
            send_id = u.id
            break
    file = enfile.objects.get(user_id=request.user.id, file_content=file_content)
    file_path = os.path.join(settings.MEDIA_ROOT, str(request.user.username), str(file_content))
    send_path = os.path.join(settings.MEDIA_ROOT, str(send_name), str(file_content))
    
    if not send_name:
        result = 'not input'
    elif not send_id:
        result = 'not id'
    elif os.path.isfile(send_path):
        result = 'aleady file'
    else:
        shutil.copyfile(file_path, send_path)

        e = enfile(user_id_id=send_id, file_text=file.file_text, file_content=file_content, send_user=request.user.username)
        e.save()
        result = 'success send'

    enlist = enfile.objects.filter(user_id=request.user.id)
    content = {'result': result, 'enlist': enlist}
    return render(request, 'encryption/mydrive.html', content)

def delete(request, file_content):
    user_directory_path = os.path.join(settings.MEDIA_ROOT, str(request.user.username))

    if file_content in os.listdir(user_directory_path):
        os.remove(os.path.join(user_directory_path, file_content))

    data = enfile.objects.get(user_id=request.user.id, file_content=file_content)
    data.delete()

    return redirect('encryption:mydrive')

class myAES():
    def __init__(self, keytext, ivtext):
        hash = SHA.new()
        hash.update(keytext.encode('utf-8'))
        key = hash.digest()
        self.key = key[:16]
        hash.update(ivtext.encode('utf-8'))
        iv = hash.digest()
        self.iv = iv[:16]

    def makeEnabled(self, plaintext):
        fillersize = 0
        textsize = len(plaintext)
        if textsize % 16 != 0:
            fillersize = 16 - textsize % 16
        filler = '0' * fillersize
        header = '%d' % (fillersize)
        gap = 16 - len(header)
        header += '#' * gap
        return header + plaintext + filler

    def enc(self, plaintext):
        a = plaintext
        me = sys.getsizeof(a)
        ik = 1
        while True:
            if ik - me >= 16:
                break
            else:
                ik += 16
        p = int((ik - me) % 16)
        list = [b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11', b'12', b'13', b'14', b'15']
        if p < 10:
            a = list[p] + b'###############' + a
        else:
            a = list[p] + b'##############' + a

        for i in range(p):
            a += b'0'
        aes = AES.new(self.key, AES.MODE_CBC, self.iv)
        encmsg = aes.encrypt(a)
        return encmsg

    def dec(self, ciphertext):
        aes = AES.new(self.key, AES.MODE_CBC, self.iv)
        decmsg = aes.decrypt(ciphertext)
        header = decmsg[:16].decode()
        fillersize = int(header.split('#')[0])
        if fillersize != 0:
            decmsg = decmsg[16:-fillersize]
        else:
            decmsg = decmsg[16:]
        return decmsg

templates/encryption/encryption.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3>파일 업로드!!</h3>
    {% if user.is_authenticated %}
    {% if result %}
    {% if 'not bin' in result %}<script>alert("확장자가 .bin인 파일만 저장가능합니다.")</script>{% endif %}
    {% if 'aleady file' in result %}<script>alert("사용자가 이미 동일한 이름의 파일을 소유하고 있습니다.")</script>{% endif %}
    {% endif %}
    <form action="mydrive" method="post" enctype="multipart/form-data" name="enfile">
        {% csrf_token %}
        <div class="form-group">
            <label for="text">파일 설명</label>
            <input type="text" class="form-control" name="text">
        </div>
        <div class="form-group">
            <label for="file">파일</label>
            <input type="file" name="fileinput">
        </div>
        <button type="submit" class="btn btn-default" onclick="ckeck();">저장하기</button>
    </form>
    {% else %}
    <p>로그인 후 이용가능</p>
    {% endif %}
</div>
{% endblock %}

templates/encryption/index.html
<!DOCTYPE html>
{% block content %}
<html lang="en" class="no-js">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>We're back</title>
	<meta name="description" content="Blueprint: A basic template for a responsive multi-level menu" />
	<meta name="keywords" content="blueprint, template, html, css, menu, responsive, mobile-friendly" />
	<meta name="author" content="Codrops" />
	<!--반응형 넣어줘야함
	<meta name="viewport" content="width=device-width,initial-scale=1">
	-->
	<link rel="shortcut icon" href="/static/assets/favicon.ico">
	<!-- demo styles -->
	<link rel="stylesheet" type="text/css" href="/static/e_css/demo.css" />
	<!-- menu styles -->
	<link rel="stylesheet" type="text/css" href="/static/e_css/component.css" />
	<link rel="stylesheet" type="text/css" href="/static/e_css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/e_css/organicfoodicons.css" />
	<script src="/static/e_js/modernizr-custom.js"></script>
	<style>
		@media (max-width: 767px){
			#encrypt-form button {
				width: 70%;
			}
		}

		/*태블릿
		@media (min-width: 768px) and (max-width: 991px) {

		}
		*/

		@media (min-width: 766px) and (max-width: 808px) {
			#encrypt-form button {

				width: 70%;
			}
		}

		@media (min-width: 1200px) {

		}

		.backgorund_form {
			max-width: 82.5%;
			margin-left: auto;
			padding: 20px;
			border-radius: 5px;
		}

		/*
		#upload-form {
			max-width: 82.5%;
			margin-left: auto;
			padding: 20px;
			border-radius: 5px;
		}
		*/

		#upload-form h1 {
			font-size: 24px;
			font-weight: bold;
			margin-bottom: 20px;
		}

		#upload-form label {
			display: block;
			margin-bottom: 10px;
			font-size: 18px;
			font-weight: bold;
		}

		#upload-form input[type=file] {
			margin-bottom: 20px;
		}

		#upload-form input[type=submit] {
			padding: 10px 20px;
			color: black;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			font-size: 15px;
			float: right;
			clear: both;
			margin-top: -90px;
		}

		#upload-form input[type=submit]:hover {
			background-color: gray;
		}

		#encrypt-form {
			max-width: 90%;
			/*margin: 0 auto;
			padding: 20px;*/
			border-radius: 5px;

		}

		#encrypt-form input[type=text] {
			padding: 10px 20px;
			font-size: 13px;
			width: 70%;
			border: none;
			border-radius: 5px;
			/*margin-left: -525px;*/
			margin-top: -200px;
		}

		#encrypt-form button {
			padding: 10px 20px;
			color: black;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			font-size: 15px;
			/*float: right;*/
			clear: both;
			/*margin-right: -820px;
			margin-right: -820px;*/
			margin-top: -10px;
		}

		#encrypt-form input[type=hidden] {
			display: none;
		}

	</style>
</head>
<body>
	<div class="container">

		<header class="bp-header cf">
			<div class="dummy-logo">
				<h2 class="dummy-heading">We're back</h2>
			</div>
		</header>

		<!--button이거 있어야 js실행됨-->
		<button class="action action--open" aria-label="Open Menu"><span class="icon icon--menu"></span></button>
		<nav id="ml-menu" class="menu">
			<button class="action action--close" aria-label="Close Menu"><span class="icon icon--cross"></span></button>
			<div class="menu__wrap">
                 {% if user.is_authenticated %}{% endif %}
				<ul data-menu="main" class="menu__level" tabindex="-1" role="menu" aria-label="ALL">
					<li><a href="{% url 'encryption:index' %}" class="menu__link" >Home</a></li>
					<li><a class="menu__link" href="{% url 'encryption:mydrive' %}">MyDrive</a></li>
					<li><a class="menu__link" href="{% url 'download_page' %}">Download</a></li>

					{% if user.is_authenticated %}
      				<li><a class="menu__link" href="{% url 'common:logout' %}">logout</a></li>
					{% else %}
					<li><a class="menu__link" href="{% url 'common:signup' %}">signup</a></li>
					<li><a class="menu__link" href="{% url 'common:login' %}">login</a></li>
					{% endif %}

				</ul>
			</div>
		</nav>

		<div class="content">
		<div class="backgorund_form">
			<p class="info">
				<div id="upload-form">
			{% if user.is_authenticated %}
    			{% if result %}
    				{% if 'not bin' in result %}<script>alert("확장자가 .bin인 파일만 저장가능합니다.")</script>{% endif %}
    						{% if 'aleady file' in result %}<script>alert("사용자가 이미 동일한 이름의 파일을 소유하고 있습니다.")</script>{% endif %}
				{% endif %}

					<form action="mydrive" method="post" enctype="multipart/form-data" name="enfile">
						{% csrf_token %}
						<div class="form-group">
						<label for="text">파일 설명</label>
            			<input type="text" class="form-control" name="text">
						</div>
						<div class="form-group">
						<label for="file">파일 선택:</label>
						<input type="file" name="fileinput">
						</div>

						<div id="encrypt-form">

						&nbsp;<button type="submit" onclick="ckeck();">저장하기</button>
						<input type="hidden" id="encrypted" name="encrypted">

						</div>
						<!--<input type="submit" class="submit-button" value="업로드">-->
					</form>
			 {% else %}
    <p>로그인 후 이용가능</p>
    {% endif %}
</div>
				</div>

			</p>
			</div>
		</div>
	</div>

</body>

	</div>
	<!-- 여기 코드부터는 아직 건든거 없음 -->
	<script src="/static/e_js/classie.js"></script>
	<script src="/static/e_js/dummydata.js"></script>
	<script src="/static/e_js/main.js"></script>
	<script>
	(function() {
		var menuEl = document.getElementById('ml-menu'),
			mlmenu = new MLMenu(menuEl, {
				// breadcrumbsCtrl : true, // show breadcrumbs
				// initialBreadcrumb : 'all', // initial breadcrumb text
				backCtrl : false, // show back button
				// itemsDelayInterval : 60, // delay between each menu item sliding animation
				onItemClick: loadDummyData // callback: item that doesn´t have a submenu gets clicked - onItemClick([event], [inner HTML of the clicked item])
			});

		// mobile menu toggle
		var openMenuCtrl = document.querySelector('.action--open'),
			closeMenuCtrl = document.querySelector('.action--close');

		openMenuCtrl.addEventListener('click', openMenu);
		closeMenuCtrl.addEventListener('click', closeMenu);

		function openMenu() {
			classie.add(menuEl, 'menu--open');
			closeMenuCtrl.focus();
		}

		function closeMenu() {
			classie.remove(menuEl, 'menu--open');
			openMenuCtrl.focus();
		}

		// simulate grid content loading
		var gridWrapper = document.querySelector('.content');

		function loadDummyData(ev, itemName) {
			ev.preventDefault();

			closeMenu();
			gridWrapper.innerHTML = '';
			classie.add(gridWrapper, 'content--loading');
			setTimeout(function() {
				classie.remove(gridWrapper, 'content--loading');
				gridWrapper.innerHTML = '<ul class="products">' + dummyData[itemName] + '<ul>';
			}, 700);
		}
	})();


	</script>
</body>

</html>
{% endblock %}

templates/encryption/mydrive.html
<!DOCTYPE html>
{% block content %}
<html lang="en" class="no-js">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>We're back</title>
	<meta name="description" content="Blueprint: A basic template for a responsive multi-level menu" />
	<meta name="keywords" content="blueprint, template, html, css, menu, responsive, mobile-friendly" />
	<meta name="author" content="Codrops" />
	<!--반응형 넣어줘야함
	<meta name="viewport" content="width=device-width,initial-scale=1">
	-->
	<link rel="shortcut icon" href="/static/assets/favicon.ico">
	<!-- demo styles -->
	<link rel="stylesheet" type="text/css" href="/static/e_css/demo.css" />
	<!-- menu styles -->
	<link rel="stylesheet" type="text/css" href="/static/e_css/component.css" />
	<link rel="stylesheet" type="text/css" href="/static/e_css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/e_css/organicfoodicons.css" />
	<script src="/static/e_js/modernizr-custom.js"></script>
	<style>
		@media (max-width: 767px){
			#encrypt-form button {
				width: 70%;
			}
		}

		/*태블릿
		@media (min-width: 768px) and (max-width: 991px) {

		}
		*/

		@media (min-width: 766px) and (max-width: 808px) {
			#encrypt-form button {

				width: 70%;
			}
		}

		@media (min-width: 1200px) {

		}

		.backgorund_form {
			max-width: 82.5%;
			margin-left: auto;
			padding: 20px;
			border-radius: 5px;
		}

		/*
		#upload-form {
			max-width: 82.5%;
			margin-left: auto;
			padding: 20px;
			border-radius: 5px;
		}
		*/

		#upload-form h1 {
			font-size: 24px;
			font-weight: bold;
			margin-bottom: 20px;
		}

		#upload-form label {
			display: block;
			margin-bottom: 10px;
			font-size: 18px;
			font-weight: bold;
		}

		#upload-form input[type=file] {
			margin-bottom: 20px;
		}

		#upload-form input[type=submit] {
			padding: 10px 20px;
			color: black;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			font-size: 15px;
			float: right;
			clear: both;
			margin-top: -90px;
		}

		#upload-form input[type=submit]:hover {
			background-color: gray;
		}

		#encrypt-form {
			max-width: 90%;
			/*margin: 0 auto;
			padding: 20px;*/
			border-radius: 5px;

		}

		#encrypt-form input[type=text] {
			padding: 10px 20px;
			font-size: 13px;
			width: 70%;
			border: none;
			border-radius: 5px;
			/*margin-left: -525px;*/
			margin-top: -200px;
		}

		#encrypt-form button {
			padding: 10px 20px;
			color: black;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			font-size: 15px;
			/*float: right;*/
			clear: both;
			/*margin-right: -820px;
			margin-right: -820px;*/
			margin-top: -10px;
		}

		#encrypt-form input[type=hidden] {
			display: none;
		}
        table{
            margin-left: 400px;
            border: 1px;
            border-color: white;
        }

	</style>
</head>
<body>
	<div class="container">

		<header class="bp-header cf">
			<div class="dummy-logo">
				<h2 class="dummy-heading">We're back</h2>
			</div>
		</header>

		<!--button이거 있어야 js실행됨-->
		<button class="action action--open" aria-label="Open Menu"><span class="icon icon--menu"></span></button>
		<nav id="ml-menu" class="menu">
			<button class="action action--close" aria-label="Close Menu"><span class="icon icon--cross"></span></button>
			<div class="menu__wrap">
                 {% if user.is_authenticated %}{% endif %}
				<ul data-menu="main" class="menu__level" tabindex="-1" role="menu" aria-label="ALL">
					<li><a href="{% url 'encryption:index' %}" class="menu__link" >Home</a></li>
					<li><a class="menu__link" href="{% url 'encryption:mydrive' %}">MyDrive</a></li>
                    <li><a class="menu__link" href="{% url 'download_page' %}">Download</a></li>

{% if user.is_authenticated %}
      				<li><a class="menu__link" href="{% url 'common:logout' %}">logout</a></li>
					{% else %}
					<li><a class="menu__link" href="{% url 'common:signup' %}">signup</a></li>
					<li><a class="menu__link" href="{% url 'common:login' %}">login</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
        <div class="container">
    <h3>드라이브!!</h3>
    {% if user.is_authenticated %}
        {% if result %}
        {% if 'not input' in result %}<script>alert("아이디를 넣었는지 확인해주세요.")</script>{% endif %}
        {% if 'not id' in result %}<script>alert("아이디가 존재하지 않습니다.")</script>{% endif %}
        {% if 'aleady file' in result %}<script>alert("사용자가 이미 동일한 이름의 파일을 소유하고 있습니다.")</script>{% endif %}
        {% if 'success send' in result%}<script>alert("공유 되었습니다.")</script>{% endif %}
        {% if 'success upload' in result%}<script>alert("저장 되었습니다.")</script>{% endif %}
        {% endif %}
    <table  class="table table-striped">
      <thead>
        <tr>
          <th width="5%">날짜</th>
          <th width="5%">설명</th>
          <th width="5%">공유자</th>
          <th width="5%">공유</th>
          <th width="5%">다운로드</th>
          <th width="5%">삭제</th>
        </tr>

      </thead>
      <tbody>
        {% for e in enlist %}
        <tr>
          <td>{{e.file_date|date:'Y-m-d H:i'}}</td>
          <td>{{e.file_text}}</td>
          <td>
            {% if e.send_user %}
            {{e.send_user}}
            {% endif %}
          </td>
          <td>
            <form method="get" action="{% url 'encryption:send' file_content=e.file_content %}" name="send">
              <input type="text" name="sendid" style="height: 2.2em" placeholder="공유할 아이디 입력">
              <button type="submit" class="btn btn-primary">공유</button>
            </form>
          </td>
          <td>
            <form method="get" action="{% url 'encryption:download' file_content=e.file_content %}">
              <button type="submit" class="btn btn-primary">다운로드</button>
            </form>
          </td>
          <td>
            <form method="get" action="{% url 'encryption:delete' file_content=e.file_content %}">
              <button type="submit" class="btn btn-danger">삭제</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
    {% else %}
    <p>로그인 후 이용가능</p>

	</div>
{% endif %}

</body>

	</div>
	<!-- 여기 코드부터는 아직 건든거 없음 -->
	<script src="/static/e_js/classie.js"></script>
	<script src="/static/e_js/dummydata.js"></script>
	<script src="/static/e_js/main.js"></script>
	<script>
	(function() {
		var menuEl = document.getElementById('ml-menu'),
			mlmenu = new MLMenu(menuEl, {
				// breadcrumbsCtrl : true, // show breadcrumbs
				// initialBreadcrumb : 'all', // initial breadcrumb text
				backCtrl : false, // show back button
				// itemsDelayInterval : 60, // delay between each menu item sliding animation
				onItemClick: loadDummyData // callback: item that doesn´t have a submenu gets clicked - onItemClick([event], [inner HTML of the clicked item])
			});

		// mobile menu toggle
		var openMenuCtrl = document.querySelector('.action--open'),
			closeMenuCtrl = document.querySelector('.action--close');

		openMenuCtrl.addEventListener('click', openMenu);
		closeMenuCtrl.addEventListener('click', closeMenu);

		function openMenu() {
			classie.add(menuEl, 'menu--open');
			closeMenuCtrl.focus();
		}

		function closeMenu() {
			classie.remove(menuEl, 'menu--open');
			openMenuCtrl.focus();
		}

		// simulate grid content loading
		var gridWrapper = document.querySelector('.content');

		function loadDummyData(ev, itemName) {
			ev.preventDefault();

			closeMenu();
			gridWrapper.innerHTML = '';
			classie.add(gridWrapper, 'content--loading');
			setTimeout(function() {
				classie.remove(gridWrapper, 'content--loading');
				gridWrapper.innerHTML = '<ul class="products">' + dummyData[itemName] + '<ul>';
			}, 700);
		}
	})();


	</script>
</body>

</html>


{% endblock %}