common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='common/login.html'), name='logout'),
    path('signup', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('common.urls')),
    path("encryption/", include('encryption.urls')),
    path("download/", include("download.urls")),
    path("py/", include("py.urls")),
]

encryption/urls.py
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'encryption'
urlpatterns = [
    path('', views.index, name='index'),
    #path('encryption', views.encryption, name='encryption'),
    path('mydrive', views.mydrive, name='mydrive'),
    path('download/<str:file_content>', views.download, name='download'),
    path('send/<str:file_content>', views.send, name='send'),
    path('delete/<str:file_content>', views.delete, name='delete'),
]

py/urls.py
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'py'
urlpatterns = [
    path('', views.index, name='index'),
    #path('encryption', views.encryption, name='encryption'),

]

templates/base_.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>파일 암호화 사이트</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">파일 암호화 사이트</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'encryption:index' %}">Home</a></li>
      <li><a href="{% url 'encryption:encryption' %}">encryption</a></li>
      <li><a href="{% url 'encryption:mydrive' %}">mydrive</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a href="{% url 'common:logout' %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
      {% else %}
      <li><a href="{% url 'common:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'common:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<script>
  function ckeck(){
    enfile = document.enfile;
    if(enfile.fileinput.value==""){
      alert("파일을 제대로 넣었는지 확인해주세요.");
    }
  }
</script>
{% block content %}
{% endblock %}